# Generated by Django 4.0.3 on 2022-05-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
