# Generated by Django 4.0.3 on 2022-05-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Likes',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
