# Generated by Django 4.0.3 on 2022-05-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_siguiendo_delete_seguidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Siguiendo',
        ),
    ]
