# Generated by Django 4.0.3 on 2022-05-05 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_delete_siguiendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siguiendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seguido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioSeguidor', to=settings.AUTH_USER_MODEL)),
                ('Seguidor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioSeguido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
