# Generated by Django 4.0.3 on 2022-05-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_seguido_user_seguidor_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Seguido',
        ),
    ]
